dist: xenial
language: python
sudo: false
cache: pip
git:
   depth: 1
python:
- 2.7
- 3.7
- pypy2.7-6.0
- pypy3.5-6.0
env:
- secure: "EhG2uSD2m1eGxuL2HeQewJJx7MVL4WpjrxyfiUBEgsApemD1yKJPjUnLwAyd\nbPi5HJx5ySm1TTRSvj6/yP85YLYTaJHA8OabKk7p0wFW294qcrYIDGovU7NL\n3YOqZmqN+S3XOBGFCOnByxE+pcxxWW/3/I09EgeW7D6tBPh67G0="
install:
- echo $TRAVIS_PYTHON_VERSION
- pip install pytest coveralls
- >
    if [[ "$TRAVIS_PYTHON_VERSION" != "pypy" && "$TRAVIS_PYTHON_VERSION" != "pypy3" ]]; then
      pip install 'pytest-cov>=1.8.0';
    fi
- >
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install --upgrade setuptools;
    fi
- pip install -e .[test] --upgrade
script:
- python -mwand.version --verbose
- >
    if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" || "$TRAVIS_PYTHON_VERSION" == "pypy3" ]]; then
      py.test --skip-pdf --skip-slow --durations=20;
    else
      py.test --skip-pdf --cov wand --durations=20;
    fi
after_success:
- coveralls
